### ISSUE TITLE
Why does max-height or min-height not work? 

### ISSUE THREAD

**Issue by hanancs** [kasinskas/react-native-media-query#9]
![image](https://user-images.githubusercontent.com/50701475/145712317-28428fa2-3137-4fce-99b0-ea2769e2e6ba.png)

I like to vary the styles according to the height of the device. Let me know how to handle it in your dependency.

**Comment by mgntr-mauro-fernandez** [comment]
@hanancs did you solve this? I'm having the same issue. I'm applying different font size and they are not working on responsive web

**Comment by hanancs** [comment]
@mgntr-mauro-fernandez I recommend you to use following package [react-native-extended-stylesheet
](https://www.npmjs.com/package/react-native-extended-stylesheet)
If you go with the package I suggested above, then you can set the media queries like we used to do on vanila CSS.
```
'@media (min-height: 500) and (max-height: 699px)': {
      marginTop: '15%'
},
```

**Comment by kasinskas** [comment]
Hi @mgntr-mauro-fernandez, I never had to rely on min/max-height tbh, but I just did a quick test on one of my projects and it does work on web. How are you using it? Did you add `dataSet` prop if you're using react-native-web, or `data-media` if you're using regular html elements?

https://user-images.githubusercontent.com/22332217/161824236-8c71c0d0-8e1f-43a0-813a-8e3c9cb59111.mov

FYI, react-native-extended-stylesheet is a great package, but it's pretty heavyweight (382kb) and if I recall correctly it doesn't support dynamic style changes and requires you to manually rerender the component for styles to switch on different breakpoints, which is not that big of an deal on native platforms (and react-native-media-query requires you to do the same), but on web it can become pretty slow, especially on window resize. Also I'm not sure if it works on server-side rendering correctly without flash of unstyled (or incorrectly styled) content on initial render. 

Since rnmq does style injections differently on web it avoids issues mentioned above. BUT if they aren't important for you then by all means please use react-native-extended-stylesheet, since it's way more feature rich as this package was created solely to fulfill my specific needs (easy, SSR, fast) and is supposed to be lightweight.

I'll add height targeting on native platforms, since it's only a few lines of code. Was swamped with work and then completely forgot about this ticket, sorry.

**Comment by kasinskas** [comment]
Added support for height, orientation and aspect-ratio media queries on native platforms in 1.0.11.

```
  useWindowDimensions(); // to update mobile styles on rotation. not needed for web

  const { ids, styles } = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "coral",
      "@media (min-height: 400px) and (max-height: 500px)": {
        backgroundColor: "teal",
      },
    },
    text: {
      "@media (orientation: landscape)": {
        color: "white",
      },
    },
  });

  return (
    <View style={styles.container} dataSet={{ media: ids.container }}>
      <Text style={styles.text} dataSet={{ media: ids.text }}>react-native-media-query</Text>
    </View>
  );
```

https://user-images.githubusercontent.com/22332217/162581457-4f33594f-d346-407a-b18b-c5fb6a0014ad.mov
